---
services:
  lgtm:
    image: grafana/otel-lgtm@sha256:10f48eb2f8670134df542177bb19536c55421b089e43f9dfc2a27d4c078204d8
    ports:
      - 3000:3000
      - 4040:4040
      - 4317:4317
      - 4318:4138
      - 9090:9090

  mongodb:
    image: mongodb/mongodb-atlas-local
    hostname: mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db:/data/db
      - configdb:/data/configdb
      - mongot:/data/mongot

volumes:
  db:
  configdb:
  mongot:
