[advisories]
version = 2
ignore = [
  { id = "RUSTSEC-2024-0436", reason = "Paste is brought in via utoipa-axum, which we use" },
]

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "MIT",
  "Unicode-3.0",
  "BSD-3-Clause",
  "ISC",
  "CC0-1.0",
  "CDLA-Permissive-2.0"
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
