---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-lint:
    name: Rust Lint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: ./.github/actions/setup-mise

      - name: Check formatting
        run: mise run fmt-check-rs

      - name: Run linter
        run: mise run lint-rs

  frontend-lint:
    name: Frontend Lint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: ./.github/actions/setup-mise

      - name: Install PNPM packages
        run: mise run install-fe

      - name: Check formatting
        run: mise run fmt-fe

      - name: Run linters
        run: mise run lint-fe

  cargo-audit:
    name: Cargo Audit
    runs-on: ubuntu-24.04
    continue-on-error: true
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: ./.github/actions/setup-mise

      - name: Run audit
        run: mise run audit
